language: cpp
sudo: required
services:
  - docker
os:
  - linux
  - osx
env:
  global:
    - MAKEFLAGS="-j2"
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull ubuntu:16.04; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew bundle; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -t drinkcoin-builder .; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -v $(pwd):/usr/src drinkcoin-builder; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash build.sh; fi
