language: cpp
sudo: required
services:
  - docker
os:
  - linux
  - osx
env:
  global:
    - MAKEFLAGS="-j2"
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull ubuntu:16.04; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew bundle; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -t drinkcoin-builder .; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -u $UID -v "$PWD":/usr/src drinkcoin-builder; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash utils/build.sh; fi
  - bash utils/package.sh
deploy:
  provider: releases
  api_key:
    secure: pMfhJg/io7H5LKb3c1PVoK8vaZnGh4Ggyc9S2A/KMKXNQ5Xb3qrFUgiOlduaA9RwvR5Lj0tmzeTaZHipRqIS5sbgIfrcOm9Dxi+kqSE9Le3lYmZQhTyFLSJJbCcwgZJYgI8iGD3eNJe5j9EFAWHobp2LBEYtTWn+uAeBa6Djd8jenhSQtLSExq55xYOE809FytovfpcsiA917L6puO4hMyVQpPj8Lswlc6VHco21R0P1qvwGnvxIGmiuEXzGSNaeRm6VPxCUEikY6bXZAc6LLwfdH/+eXI5gXScBGpW4BZE6V4u817eOg8npBPtViWzmB+9B5Z3bjQ8J3CQ2e7nqGZ224J+3tfcqzVwPpSdRqjxN4oNLCtHGJ7oDlpLyhmCmKoCF/NyvRoJtpF00sYUIII5UMYoAFeTOVirOXjEYy3LO/QP6jjfP5ifdfXJpugT1sYgRQIep/teHqbN1iNJTyCp7gvJ1/oClhFFGCztNd4QCeg4SmUxyhI4teLGn9xyH5TEMuHliSfQ1hkGPoLdWGvVWjiFIUjJHszfm4yPbzoDvW4eqSX0287TW+osfRBY64JHmPtxyOFYAGnZWMPKbZ0fPO+S7gn/VVVrRfeY99pr8JP34Yaen6biel5bWHYhis+pJAvjBpeZCDd5k1PPRZaAeyPJ2kShwE0+iTIFXAeU=
  file_glob: true
  file: build/packages/drinkcoin-*.tar.gz
  skip_cleanup: true
  on:
    repo: ComputerScienceHouse/drinkcoin
    tags: true
