version: "{build}"
image: Visual Studio 2013
platform: x64
clone_folder: C:\drinkcoin
environment:
  BOOST_ROOT: C:\Libraries\boost_1_58_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_58_0\lib64-msvc-12.0
install:
  - mkdir C:\drinkcoin\build\release
  - cd C:\drinkcoin\build\release
  - cmake -G "Visual Studio 12 Win64" "..\.."
configuration: Release
build:
  parallel: true
  project: C:\drinkcoin\build\release\Bytecoin.sln
deploy: off
